version: 2

before:
  hooks:
    - go mod tidy
builds:
  - main: ./cmd/kunnus/
    id: kunnus
    binary: kunnus
    env:
      # goreleaser does not work with CGO, it could also complicate
      # usage by users in CI/CD systems like Terraform Cloud where
      # they are unable to install libraries.
      - CGO_ENABLED=0
      - GO111MODULE=on
    mod_timestamp: "{{ .CommitTimestamp }}"
    flags:
      - -trimpath
    ldflags:
      - "-s -w"
      - "-X github.com/google/osv-scanner/v2/cmd/kunnus/internal/version.KunnusVersion={{.Version}}.nightly"
      - "-X main.commit={{.Commit}}"
      - "-X main.date={{.CommitDate}}"
    goos:
      - linux
    goarch:
      - amd64

dockers_v2:
  # Main kunnus image
  - id: kunnus
    dockerfile: goreleaser.dockerfile
    ids:
      - kunnus
    images:
      - "ghcr.io/think-ahead-technologies/kunnus-scanner"
    tags:
      - "nightly"
    labels:
      "org.opencontainers.image.title": "kunnus"
      "org.opencontainers.image.description": "Vulnerability scanner written in Go which uses the data provided by https://osv.dev"
      "org.opencontainers.image.licenses": "Apache License 2.0"
      "org.opencontainers.image.created": "{{.Date}}"
      "org.opencontainers.image.name": "{{.ProjectName}}"
      "org.opencontainers.image.revision": "{{.FullCommit}}"
      "org.opencontainers.image.version": "{{.Version}}"
      "org.opencontainers.image.source": "{{.GitURL}}"
      "org.opencontainers.image.url": "{{.GitURL}}"
    platforms:
      - linux/amd64
  # GitHub Actions variant
  - id: kunnus-action
    dockerfile: goreleaser-action.dockerfile
    ids:
      - kunnus
    images:
      - "ghcr.io/think-ahead-technologies/kunnus-scanner-action"
    tags:
      - "nightly"
    labels:
      "org.opencontainers.image.title": "kunnus-action"
      "org.opencontainers.image.description": "Vulnerability scanner written in Go which uses the data provided by https://osv.dev"
      "org.opencontainers.image.licenses": "Apache-2.0"
      "org.opencontainers.image.created": "{{.Date}}"
      "org.opencontainers.image.name": "{{.ProjectName}}"
      "org.opencontainers.image.revision": "{{.FullCommit}}"
      "org.opencontainers.image.version": "{{.Version}}"
      "org.opencontainers.image.source": "{{.GitURL}}"
      "org.opencontainers.image.url": "{{.GitURL}}"
    extra_files:
      - exit_code_redirect.sh
    platforms:
      - linux/amd64

release:
  disable: true
changelog:
  disable: true
