version: 2

before:
  hooks:
    - go mod tidy
builds:
  - main: ./cmd/kunnus/
    id: kunnus
    binary: kunnus
    env:
      # goreleaser does not work with CGO, it could also complicate
      # usage by users in CI/CD systems like Terraform Cloud where
      # they are unable to install libraries.
      - CGO_ENABLED=0
      - GO111MODULE=on
    mod_timestamp: "{{ .CommitTimestamp }}"
    flags:
      - -trimpath
    ldflags:
      - "-s -w"
      - "-X github.com/google/osv-scanner/v2/cmd/kunnus/internal/version.KunnusVersion={{.Version}}.nightly"
      - "-X main.commit={{.Commit}}"
      - "-X main.date={{.CommitDate}}"
    goos:
      - linux
    goarch:
      - amd64

dockers:
  # Main kunnus image
  - image_templates:
      - "ghcr.io/think-ahead-technologies/kunnus-scanner:nightly"
    dockerfile: goreleaser.dockerfile
    use: buildx
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.title=kunnus"
      - "--label=org.opencontainers.image.description=Vulnerability scanner written in Go which uses the data provided by https://osv.dev"
      - "--label=org.opencontainers.image.licenses=Apache License 2.0"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.name={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.source={{.GitURL}}"
      - "--label=org.opencontainers.image.url={{.GitURL}}"
      - "--platform=linux/amd64"
  # Github Action
  - image_templates:
      - "ghcr.io/think-ahead-technologies/kunnus-scanner-action:nightly"
    dockerfile: goreleaser-action.dockerfile
    use: buildx
    extra_files:
      - exit_code_redirect.sh
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.title=kunnus-action"
      - "--label=org.opencontainers.image.description=Vulnerability scanner written in Go which uses the data provided by https://osv.dev"
      - "--label=org.opencontainers.image.licenses=Apache-2.0"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.name={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.source={{.GitURL}}"
      - "--label=org.opencontainers.image.url={{.GitURL}}"
      - "--platform=linux/amd64"
    goarch: amd64

release:
  disable: true
changelog:
  disable: true
