// ABOUTME: Boundary types between the planner (mode) and the encoder (sbom).
// ABOUTME: Lives in its own package so neither side depends on the other for naming.
package bom

// Component type values for ComponentInfo.Type. These are the CycloneDX
// `metadata.component.type` strings; we list them here because every
// SBOM kunnus emits has to commit to one of these for its root component.
const (
	ComponentTypeApplication = "application"
	ComponentTypeOS          = "operating-system"
	ComponentTypeFirmware    = "firmware"
	ComponentTypeLibrary     = "library"
	ComponentTypeContainer   = "container"
)

// Lifecycle is the CycloneDX metadata.lifecycles phase recording the SBOM's
// generation context (a CISA minimum element): where in the product lifecycle
// the document was produced. Each mode declares its phase — analysing source
// is pre-build, analysing built artifacts is post-build.
type Lifecycle string

const (
	// LifecyclePreBuild marks an SBOM generated from source code before a
	// build (repo mode: manifests and lockfiles, not artifacts).
	LifecyclePreBuild Lifecycle = "pre-build"
	// LifecyclePostBuild marks an SBOM generated by analysing built artifacts
	// (os and container modes: installed packages, binaries, image layers).
	LifecyclePostBuild Lifecycle = "post-build"
)

// Author identifies the entity that authored the SBOM document: per CISA's
// minimum elements, the entity *operating* the scanner, not the tool itself.
// The zero value means "not specified" — the encoder falls back to the kunnus
// creator identity so the document always carries an author.
type Author struct {
	Name  string
	Email string // optional
}

// IsZero reports whether no author was specified.
func (a Author) IsZero() bool { return a.Name == "" && a.Email == "" }

// ComponentInfo describes the root component of the resulting SBOM.
// CycloneDX puts this in metadata.component.
type ComponentInfo struct {
	Name    string
	Version string
	Type    string // one of ComponentType* constants above

	// ID is a stable identity for the scanned component, used to derive the
	// SBOM serial-number series (see Series). Empty when no stable identity is
	// known — modes only set it when the target itself carries one (a container
	// image's repository path); the user supplies it otherwise.
	ID string
}

// Series identifies the document series an SBOM belongs to: successive scans
// of the same component produce documents sharing one serial number, ordered
// by document version. The serial derivation keys on Mode+ID+Version. The
// zero value means "no stable identity": the encoder falls back to a random
// serial per run, making each document a series of one.
type Series struct {
	// Mode is the scan mode name ("repo", "os", "container"). Part of the key:
	// a repo SBOM and an os SBOM of the same component are different documents
	// with different generation semantics, so they must not share a series.
	Mode string

	// ID is the stable component identity. Empty when unknown.
	ID string

	// Version is the component version. Empty when unknown — an empty version
	// still yields a stable key; supplying one later deliberately splits the
	// series (CISA keys a series on the name/version pair).
	Version string

	// Serial is an explicit serial-number override in urn:uuid form. When set
	// it wins over derivation, letting build systems align the series with
	// their own PLM identifiers.
	Serial string
}

// ExtraComponent is one BOM component sourced outside scalibr. The fields are
// the minimum a CycloneDX library entry needs; everything else (hashes,
// per-file properties) flows through a hashes.Map keyed on PURL.
type ExtraComponent struct {
	// PURL is the package-url for the component. Vendored libs use the
	// pkg:generic type with a vendored_path qualifier.
	PURL string

	// Name is the short human-readable name (the vendored directory's basename).
	Name string

	// Version is the component version. Optional — empty for vendored libraries
	// (no version is known), set for the operating-system component of a
	// container scan.
	Version string

	// Type is the CycloneDX component type — "library" for vendored sources,
	// "operating-system" for a container image's OS.
	Type string

	// BomRef is a stable identifier within the BOM ("vendored:<rel-path>").
	BomRef string
}
