// ABOUTME: Tests for yarn.lock hash extraction across v1 and berry formats.
// ABOUTME: v1 uses "integrity sha512-<base64>", berry uses "checksum: <hex sha512>".
package lockfiles

import (
	"strings"
	"testing"

	"github.com/think-ahead/kunnus-scanner/internal/hashes"
)

func TestParseYarnLock_V1(t *testing.T) {
	content := `# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
# yarn lockfile v1


"lodash@^4.17.0":
  version "4.17.21"
  resolved "https://registry.yarnpkg.com/lodash/-/lodash-4.17.21.tgz#abc"
  integrity ` + lodashIntegrity + `

"@babel/core@^7.0.0":
  version "7.0.0"
  resolved "https://registry.yarnpkg.com/@babel/core/-/core-7.0.0.tgz#xyz"
  integrity ` + babelIntegrity + `
`
	path := writeFixture(t, "yarn.lock", content)

	got, err := parseYarnLock(path)
	if err != nil {
		t.Fatalf("parseYarnLock v1: %v", err)
	}
	for _, want := range []string{"pkg:npm/lodash@4.17.21", "pkg:npm/%40babel/core@7.0.0"} {
		if _, ok := got[want]; !ok {
			t.Errorf("missing %q: %v", want, got)
		}
	}
}

func TestParseYarnLock_Berry(t *testing.T) {
	// Yarn berry uses hex SHA-512 directly. We synthesise a value of the
	// right shape (128 hex chars) since real yarn berry checksums are also
	// 128-hex.
	checksum := strings.Repeat("ab", 64)
	content := `# This file is generated by running "yarn install" inside your project.
# Manual changes might be lost - proceed with caution!

__metadata:
  version: 8
  cacheKey: 10c0

"lodash@npm:4.17.21":
  version: 4.17.21
  resolution: "lodash@npm:4.17.21"
  checksum: ` + checksum + `
  languageName: node
  linkType: hard
`
	path := writeFixture(t, "yarn.lock", content)

	got, err := parseYarnLock(path)
	if err != nil {
		t.Fatalf("parseYarnLock berry: %v", err)
	}
	h, ok := firstHash(t, got, "pkg:npm/lodash@4.17.21")
	if !ok {
		t.Fatalf("missing lodash: %v", got)
	}
	if h.Algorithm != hashes.AlgSHA512 {
		t.Errorf("algo = %q, want SHA-512", h.Algorithm)
	}
	if h.Hex != checksum {
		t.Errorf("hex = %q, want %q", h.Hex, checksum)
	}
}

func TestParseYarnLock_SkipsNonSha512_V1(t *testing.T) {
	content := `# yarn lockfile v1

"old@^1":
  version "1.0.0"
  integrity sha1-abcdefghijklmnopqrstuvwxyz12
`
	path := writeFixture(t, "yarn.lock", content)
	got, _ := parseYarnLock(path)
	if _, ok := got["pkg:npm/old@1.0.0"]; ok {
		t.Errorf("sha1 entry must be skipped, got %v", got)
	}
}

func TestParseYarnLock_SkipsWrongLengthBerryChecksum(t *testing.T) {
	// Berry may produce non-sha512 checksums in some configurations; only
	// 128-hex strings are accepted.
	content := `__metadata:
  version: 8

"foo@npm:1.0.0":
  version: 1.0.0
  resolution: "foo@npm:1.0.0"
  checksum: deadbeef
`
	path := writeFixture(t, "yarn.lock", content)
	got, _ := parseYarnLock(path)
	if _, ok := got["pkg:npm/foo@1.0.0"]; ok {
		t.Errorf("short checksum must be skipped, got %v", got)
	}
}

func TestParseYarnLock_MissingFile(t *testing.T) {
	if _, err := parseYarnLock("/no/such/yarn.lock"); err == nil {
		t.Error("want error for missing file")
	}
}
