name: Dependencies

on:
  schedule:
    # weekly on Mondays at 06:47 UTC
    - cron: "47 6 * * 1"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

# Restrict jobs in this workflow to have no permissions by default; permissions
# should be granted per job as needed using a dedicated `permissions` block
permissions: {}

jobs:
  update:
    permissions:
      contents: write # to fetch and commit code
      pull-requests: write # to open a PR
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      - uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6.5.0
        with:
          go-version-file: "go.mod"
          check-latest: true
      - id: update
        run: |
          latest_commit=$(git ls-remote https://github.com/google/osv-scalibr.git HEAD | cut -f1)
          echo "updating osv-scalibr to $latest_commit"
          go get github.com/google/osv-scalibr@"$latest_commit"
          go mod tidy
          echo "latest_scalibr_commit=$latest_commit" >> "$GITHUB_OUTPUT"
      - run: go test ./... || true
      - uses: peter-evans/create-pull-request@5f6978faf089d4d20b00c7766989d076bb2fc7f1 # v8.1.1
        with:
          token: ${{ secrets.PR_TOKEN_BOT }}
          title: "feat: update osv-scalibr"
          body: |
            Bumps `osv-scalibr` to https://github.com/google/osv-scalibr/commit/${{ steps.update.outputs.latest_scalibr_commit }}
          branch: "bot/update-scalibr"
          commit-message: "feat: update osv-scalibr to ${{ steps.update.outputs.latest_scalibr_commit }}"
          delete-branch: true
