name: Pre-release check

on:
  workflow_dispatch:
    inputs:
      version:
        description: "The version tag to release (e.g. v1.2.3)"
        required: true
        type: string
      commit:
        description: "The commit hash to release"
        required: true
        type: string

# Restrict jobs in this workflow to have no permissions by default; permissions
# should be granted per job as needed using a dedicated `permissions` block
permissions: {}

jobs:
  tidy:
    permissions:
      contents: read
    name: go mod tidy
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
          ref: ${{ inputs.commit }}
      - name: Set up Go
        uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version-file: "go.mod"
          check-latest: true
      - run: go mod tidy -diff
  lint:
    permissions:
      contents: read
    name: golangci-lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
          ref: ${{ inputs.commit }}
      - name: Set up Go
        uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version-file: "go.mod"
          check-latest: true
      - name: Run lint action
        uses: ./.github/workflows/lint-action
  tests:
    permissions:
      contents: read
    name: Run unit tests
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Check out code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
          ref: ${{ inputs.commit }}
      - name: Set up Go
        uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version-file: "go.mod"
          check-latest: true
      - name: Run test action
        uses: ./.github/workflows/test-action
  release-helper:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    needs:
      - tidy
      - lint
      - tests
    steps:
      - name: Print release script
        env:
          OUTPUT: |
            git tag ${{ inputs.version }} ${{ inputs.commit }} &&
            git push origin ${{ inputs.version }}
        shell: bash
        run: |
          echo "$OUTPUT"
